steps:
  # Instala las dependencias del proyecto
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
  # Compila la aplicación de Next.js para producción
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
  # Despliega la aplicación en Firebase App Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'apphosting'
      - 'backends'
      - 'deploy'
      - '${_BACKEND_ID}'
      - '--region=${_REGION}'
      - '--source=.'
      
substitutions:
  _BACKEND_ID: ''
  _REGION: 'us-central1'
